### ISSUE TITLE
使用不了，报错

### ISSUE THREAD

**Issue by Ringzer369** [dogdie233/LiarsBarEnhance#14]
报错
![屏幕截图 2024-10-22 211650](https://github.com/user-attachments/assets/6dbd3e75-546f-417b-afa2-d1c56c6fab05)
![屏幕截图 2024-10-22 211658](https://github.com/user-attachments/assets/25ea1713-a81a-44b7-836c-4a81a93f36d3)

**Comment by Ringzer369** [comment]
[
![屏幕截图 2024-10-22 212425](https://github.com/user-attachments/assets/b462a4e6-97af-44f9-a277-00640d06318d)
![屏幕截图 2024-10-22 212432](https://github.com/user-attachments/assets/a63dfeaf-b1c7-4e74-9fed-f0c54f2b812b)
](url)

**Comment by Ringzer369** [comment]
![屏幕截图 2024-10-22 212709](https://github.com/user-attachments/assets/1623941e-5571-4ecd-8aa5-61a3f6bd77d2)
![屏幕截图 2024-10-22 212713](https://github.com/user-attachments/assets/aa26f3de-6df1-43d7-b1e5-3c3c77f79392)

**Comment by Ringzer369** [comment]
满屏都是warning，然后接一个erro

**Comment by dogdie233** [comment]
这些是游戏自身就有的警告和错误，和本插件无关

**Comment by dogdie233** [comment]
如果看到
```
[Info   :   BepInEx] Loading [LiarsBarEnhance 1.0.0]
[Info   :LiarsBarEnhance] Plugin com.github.dogdie233.LiarsBarEnhance is loaded!
```
说明插件已经加载
