### ISSUE TITLE
5.在项目根目录执行dotnet build -c Release出现问题

### ISSUE THREAD

**Issue by laobideng123** [dogdie233/LiarsBarEnhance#15]
F:\SteamLibrary\steamapps\common\Liar's Bar\LiarsBarEnhance-master\lib>dotnet build -c Release
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application 'build' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download
出现这种报错，是我的根目录没有CD好还是我的sdk下载有问题呢？

**Comment by TianMengLucky** [comment]
翻译没装.NET SDK，话说有构建好的为什么要手动构建

**Comment by dogdie233** [comment]
可能是因为你下的是runtime不是sdk

**Comment by laobideng123** [comment]
> 翻译没装.NET SDK，话说有构建好的为什么要手动构建
不明白什么意思，我是新手不太懂这个

**Comment by dogdie233** [comment]
按照正常流程安装，自行构建那部分不用看

**Comment by laobideng123** [comment]
> 按照正常流程安装，自行构建那部分不用看

我是电脑小白，这个在项目根目录执行dotnet build -c Release，是在cmd命令行里面CD到这个master文件里面的lib然后输入dotnet build -c Release这个代码吗？

**Comment by laobideng123** [comment]
我看了一下是我的SDK没安装好
C:\Users\老比登>dotnet --version
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application '--version' does not exist.
  * You intended to execute a .NET SDK command:
      It was not possible to find any installed .NET SDKs.
      Install a .NET SDK from:
        https://aka.ms/dotnet-download

**Comment by laobideng123** [comment]
> 按照正常流程安装，自行构建那部分不用看
我明白了，那个放在BepInEx/plugins里面的com.github.dogdie233.LiarsBarEnhance.dll其实就是构建好的是把，有这个就行了
