### ISSUE TITLE
影响游戏平衡

### ISSUE THREAD

**Issue by CLCK0622** [dogdie233/LiarsBarEnhance#19]
这个插件是可以看到别人的骰子的，在抬杯子的时候过去看，骰子上面会有点数，感觉影响游戏公平了

**Comment by dogdie233** [comment]
啊，这样吗，我没测试过那个诶
得想点办法，确定看到的点数是真实的吗

**Comment by CLCK0622** [comment]
> 啊，这样吗，我没测试过那个诶 得想点办法，确定看到的点数是真实的吗

是真实的 确认过了 虽然颜色很浅很难辨认但是确实是对的

**Comment by dogdie233** [comment]
这样啊，得想想怎么搞

**Comment by halfcrosss** [comment]
> 这样啊，得想想怎么搞

那个骰子其实不用这个也能看到

**Comment by halfcrosss** [comment]
> > 这样啊，得想想怎么搞
> 
> 那个骰子其实用这个也能看到

打错了，不用这个也能看到

**Comment by halfcrosss** [comment]
刚刚看了下，杯子扣上也能穿模进去看

**Comment by dogdie233** [comment]
这下不影响平衡了（）
