### ISSUE TITLE
C#很复杂 

### ISSUE THREAD

**Issue by xzh051109** [dogdie233/LiarsBarEnhance#2]
可以增加imgui菜单吗 DLL很复杂 我进入游戏什么都没有 希望可以变成程序载入

**Comment by dogdie233** [comment]
暂时没有这个计划，操作都写在readme里了

**Comment by sadzsd** [comment]
纯小白不太懂，作者可以给个联系方式吗，可付费 真的想弄懂

**Comment by dogdie233** [comment]
> 纯小白不太懂，作者可以给个联系方式吗，可付费 真的想弄懂

谢邀，插件所有的功能的操作指南都写在README里了，不需要游戏内UI  
安装教程可以自己在网上找

**Comment by dogdie233** [comment]
bepinEx5的安装教程很多，自己找可以提升自己的搜索能力
就算没有这个游戏的安装教程，也可以参考其他游戏的bepin5安装教程，照葫芦画瓢学会安装
插件安装完成之后游戏内不会有任何提示，如果成功安装并`启用控制台`的话，可以在日志里看到一行日志表示插件已经启用了

**Comment by killerfrost22** [comment]
> 纯小白不太懂，作者可以给个联系方式吗，可付费 真的想弄懂

https://docs.bepinex.dev/articles/user_guide/installation/index.html?tabs=tabid-win

**Comment by dogdie233** [comment]
https://www.bilibili.com/read/cv8997496/
