### ISSUE TITLE
伸头功能别人看不到了呀

### ISSUE THREAD

**Issue by ChongZhiCZ** [dogdie233/LiarsBarEnhance#21]

**Comment by dogdie233** [comment]
怎么惠事呢

**Comment by Anypsotis** [comment]
我正在使用翻译器，但我可以确认这个问题。几个小时前更新后，其他玩家看不到头部运动和嘴巴张开

**Comment by DistanceV** [comment]
被弱智官方修复了，现在除了移动位置，其它全部失效，只能自己看得到，别人看不到

**Comment by ChongZhiCZ** [comment]
> 怎么惠事呢

应该是更新导致的吧 老板修复一下呀

**Comment by TianMengLucky** [comment]
新版本似乎已修复

**Comment by TianMengLucky** [comment]
> 新版本似乎已修复

![image](https://github.com/user-attachments/assets/a1d430f2-399a-44ec-ad31-6d84b6420ba4)

**Comment by ChongZhiCZ** [comment]
> > 新版本似乎已修复
> 
> ![image](https://private-user-images.githubusercontent.com/107238739/380419933-a1d430f2-399a-44ec-ad31-6d84b6420ba4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NDM2NTYsIm5iZiI6MTcyOTk0MzM1NiwicGF0aCI6Ii8xMDcyMzg3MzkvMzgwNDE5OTMzLWExZDQzMGYyLTM5OWEtNDRlYy1hZDMxLTZkODRiNjQyMGJhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQxMTQ5MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MjRkYmVlOWU1N2MzYjE3NzFkY2NhNTk5MTI0NWExN2U4NjUxYmI4ODUxOWViNmQ4ODg3YjY4YTA1ZjQzMWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JgzOkQdob4Tg1F6LMTH8dAoWbxqYhPv8DK-FUynTPeE)

快乐没了

**Comment by dogdie233** [comment]
> > 怎么惠事呢
> 
> 应该是更新导致的吧 老板修复一下呀

修不了（）
本来有这个功能就是官方偷懒导致的

**Comment by dogdie233** [comment]
不过官方这个修复纯纯的掩耳盗铃
因为所谓的阻止头的移动造成的作弊
并不是阻止了客户端的操作
仅仅只是头部的位置数据不同步给其他客户端
即便对方真的通过移动头部进行作弊，也只是其他玩家不知道他在作弊而已
