### ISSUE TITLE
Suggection for binding keys

### ISSUE THREAD

**Issue by Etakind** [dogdie233/LiarsBarEnhance#23]
For 98 or less keyboard users, there may be no Home, Insert keys on keyboard.

**Comment by dogdie233** [comment]
@MianbaO-o 交给你了（）

**Comment by MianbaO-o** [comment]
> For 98 or less keyboard users, there may be no Home, Insert keys on keyboard.

已经将按键修改为 F1切换锁定开关 F2开关提示 F3恢复头部 F4恢复身体

**Comment by Etakind** [comment]
非常感谢，这对于希望改键但又不是代码开发者的玩家来说是个极好的消息
