### ISSUE TITLE
关于身体移动的建议和一些商家售卖插件的问题

### ISSUE THREAD

**Issue by WuHuAKA** [dogdie233/LiarsBarEnhance#3]
出牌时需要按a和d，现在的设置一按a或者d身体就会移动，感觉有点影响操作，我建议用UHJK或者YGHJ等空闲键位控制身体移动，最好能加一个复位键，希望作者大大采纳
而且最近在b站看到很多卖和您的插件类似功能的奸商，卖到了20或者30，不清楚是不是您创作的，但是如果想维权可以去那边了解一下

最后感谢您开源了这些有趣的功能，让我和朋友打牌更有乐趣

**Comment by WuHuAKA** [comment]
看了看代码，WASD的问题已经可以解决了，复位功能希望您能考虑一下

**Comment by dogdie233** [comment]
> 出牌时需要按a和d，现在的设置一按a或者d身体就会移动，感觉有点影响操作

所以出牌的时候不能移动

> 最好能加一个复位键

忘记写readme了，按`delete`键能复位

> 而且最近在b站看到很多卖和您的插件类似功能的奸商，卖到了20或者30，不清楚是不是您创作的

目测不是我创作的，他们在我写之前就开始卖了，当然也不排除有卖这个插件的

**Comment by WuHuAKA** [comment]
了解了，谢谢

**Comment by WuHuAKA** [comment]
对了提醒一下，我看readme里面shift升高和ctrl下降的功能也没写，您下次更新可以加一下

**Comment by dogdie233** [comment]
> 对了提醒一下，我看readme里面shift升高和ctrl下降的功能也没写，您下次更新可以加一下

草我又忘了，感谢提醒
