### ISSUE TITLE
release崩了，安装和自己构建都要做吗，不很很懂，感谢大佬。

### ISSUE THREAD

**Issue by zhemingbuhuichong** [dogdie233/LiarsBarEnhance#4]

**Comment by dogdie233** [comment]
不需要自己构建，从release下载dll，装好bepin5之后放进bepinex/plugins文件夹就行了

**Comment by NarwhalChen** [comment]
但是release目前打开显示404，并且自己构建的话按照readme构建之后报错
PS C:\et\LiarsBarEnhance> dotnet build -c Release
  Determining projects to restore...
C:\et\LiarsBarEnhance\LiarsBarEnhance.csproj : error NU1101: Unable to find package BepInEx.Analyzers. No packages exi
st with this id in source(s): nuget.org [C:\et\LiarsBarEnhance\LiarsBarEnhance.sln]
C:\et\LiarsBarEnhance\LiarsBarEnhance.csproj : error NU1101: Unable to find package BepInEx.Core. No packages exist wi
th this id in source(s): nuget.org [C:\et\LiarsBarEnhance\LiarsBarEnhance.sln]
C:\et\LiarsBarEnhance\LiarsBarEnhance.csproj : error NU1101: Unable to find package BepInEx.PluginInfoProps. No packag
es exist with this id in source(s): nuget.org [C:\et\LiarsBarEnhance\LiarsBarEnhance.sln]
C:\et\LiarsBarEnhance\LiarsBarEnhance.csproj : error NU1101: Unable to find package HarmonyLib. No packages exist with
 this id in source(s): nuget.org [C:\et\LiarsBarEnhance\LiarsBarEnhance.sln]
  Failed to restore C:\et\LiarsBarEnhance\LiarsBarEnhance.csproj (in 999 ms).

Build FAILED.

C:\et\LiarsBarEnhance\LiarsBarEnhance.csproj : error NU1101: Unable to find package BepInEx.Analyzers. No packages exi
st with this id in source(s): nuget.org [C:\et\LiarsBarEnhance\LiarsBarEnhance.sln]
C:\et\LiarsBarEnhance\LiarsBarEnhance.csproj : error NU1101: Unable to find package BepInEx.Core. No packages exist wi
th this id in source(s): nuget.org [C:\et\LiarsBarEnhance\LiarsBarEnhance.sln]
C:\et\LiarsBarEnhance\LiarsBarEnhance.csproj : error NU1101: Unable to find package BepInEx.PluginInfoProps. No packag
es exist with this id in source(s): nuget.org [C:\et\LiarsBarEnhance\LiarsBarEnhance.sln]
C:\et\LiarsBarEnhance\LiarsBarEnhance.csproj : error NU1101: Unable to find package HarmonyLib. No packages exist with
 this id in source(s): nuget.org [C:\et\LiarsBarEnhance\LiarsBarEnhance.sln]
    0 Warning(s)
    4 Error(s)

Time Elapsed 00:00:01.32，我是直接跳到自己构建了，是需要先安装bepinx吗？那这样的话readme步骤有点不太好理解

**Comment by dogdie233** [comment]
release链接打错了，不好意思哈（）
~~自己构建要先添加bepinex的nuget api index~~我添加进csproj里了，你pull一下就可以构建了

**Comment by NarwhalChen** [comment]
> release链接打错了，不好意思哈（） ~自己构建要先添加bepinex的nuget api index~我添加进csproj里了，你pull一下就可以构建了

okok搞定了，感谢大佬
