### ISSUE TITLE
还原项目时出现错误

### ISSUE THREAD

**Issue by Ha07aNccc** [dogdie233/LiarsBarEnhance#9]
在倒数第二步骤时执行代码说还原出现错误怎么解决呢

**Comment by Ha07aNccc** [comment]
还有可以麻烦您告诉我那个项目根文件夹是否是在你的页面下载的那个呢

**Comment by sadzsd** [comment]
再麻烦问下这个dll文件在哪里呢

**Comment by Ha07aNccc** [comment]
在安装步骤里第二项Release是一个链接 可以点进去下载

**Comment by dogdie233** [comment]
还原失败猜测是因为你没有把游戏的dll文件放入lib文件夹
请执行4. 复制游戏的所有dll进lib文件夹（位于<游戏根目录>/Liar's Bar_Data/Managed/）

**Comment by Ha07aNccc** [comment]
我把所有的dll文件复制进去了 还是还原失败

**Comment by Ha07aNccc** [comment]
需要把下载的那个dll文件放进去吗

**Comment by Ha07aNccc** [comment]
需要把下载的那个dll文件放进去吗

**Comment by Tzzzzz05** [comment]
我也是倒数第二部出问题，还原不了

**Comment by dogdie233** [comment]
> 我把所有的dll文件复制进去了 还是还原失败

看看日志

**Comment by dogdie233** [comment]
把游戏的所有dll复制进lib文件夹之后，lib文件夹里面会有很多个dll文件，比如Assembly-CSharp.dll

**Comment by Tzzzzz05** [comment]
![Uploading QQ20241022-133823.png…]()

**Comment by Tzzzzz05** [comment]
![Uploading QQ20241022-134003.png…]()

**Comment by dogdie233** [comment]
哥你图没发上来

**Comment by pzyruo** [comment]
这个还原得多久，我半天不带动的。

**Comment by na20215** [comment]
> 哥你图没发上来

这哥们太逗了，我估计是这次更新文件出现变动了吧。
确实失败了：
C:\Users\10433\Downloads\LiarsBarEnhance-master\Features\RemoveHeadRotationlimitPatch.cs(14,13): warning Harmony003: Ha
rmony non-ref patch parameter lfAngle += 360f modified. This assignment have no effect. [C:\Users\10433\Downloads\Liars
BarEnhance-master\LiarsBarEnhance.csproj]
C:\Users\10433\Downloads\LiarsBarEnhance-master\Features\RemoveHeadRotationlimitPatch.cs(16,13): warning Harmony003: Ha
rmony non-ref patch parameter lfAngle -= 360f modified. This assignment have no effect. [C:\Users\10433\Downloads\Liars
BarEnhance-master\LiarsBarEnhance.csproj]
C:\Users\10433\Downloads\LiarsBarEnhance-master\Plugin.cs(28,42): error CS0246: 未能找到类型或命名空间名“SelectableLevelPatch”(是否缺少
 using 指令或程序集引用?) [C:\Users\10433\Downloads\LiarsBarEnhance-master\LiarsBarEnhance.csproj]
C:\Users\10433\Downloads\LiarsBarEnhance-master\Plugin.cs(28,72): error CS0103: 当前上下文中不存在名称“SelectableLevelPatch” [C:\U
sers\10433\Downloads\LiarsBarEnhance-master\LiarsBarEnhance.csproj]
    2 个警告
    2 个错误
<img width="853" alt="cf53e3090d5a408342f8e327b7e1c3d" src="https://github.com/user-attachments/assets/255ad410-c667-4605-8cce-c9ed52fc6c47">

**Comment by na20215** [comment]
> > 哥你图没发上来
> 
> 这哥们太逗了，我估计是这次更新文件出现变动了吧。 确实失败了： C:\Users\10433\Downloads\LiarsBarEnhance-master\Features\RemoveHeadRotationlimitPatch.cs(14,13): warning Harmony003: Ha rmony non-ref patch parameter lfAngle += 360f modified. This assignment have no effect. [C:\Users\10433\Downloads\Liars BarEnhance-master\LiarsBarEnhance.csproj] C:\Users\10433\Downloads\LiarsBarEnhance-master\Features\RemoveHeadRotationlimitPatch.cs(16,13): warning Harmony003: Ha rmony non-ref patch parameter lfAngle -= 360f modified. This assignment have no effect. [C:\Users\10433\Downloads\Liars BarEnhance-master\LiarsBarEnhance.csproj] C:\Users\10433\Downloads\LiarsBarEnhance-master\Plugin.cs(28,42): error CS0246: 未能找到类型或命名空间名“SelectableLevelPatch”(是否缺少 using 指令或程序集引用?) [C:\Users\10433\Downloads\LiarsBarEnhance-master\LiarsBarEnhance.csproj] C:\Users\10433\Downloads\LiarsBarEnhance-master\Plugin.cs(28,72): error CS0103: 当前上下文中不存在名称“SelectableLevelPatch” [C:\U sers\10433\Downloads\LiarsBarEnhance-master\LiarsBarEnhance.csproj] 2 个警告 2 个错误 <img alt="cf53e3090d5a408342f8e327b7e1c3d" width="853" src="https://private-user-images.githubusercontent.com/78482004/379009025-255ad410-c667-4605-8cce-c9ed52fc6c47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MjkzNTIsIm5iZiI6MTcyOTYyOTA1MiwicGF0aCI6Ii83ODQ4MjAwNC8zNzkwMDkwMjUtMjU1YWQ0MTAtYzY2Ny00NjA1LThjY2UtYzllZDUyZmM2YzQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDIwMzA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxY2ExNTI3NWQyNWQ4NjhhNDQ5ZmUxNmY1MDU4ZjI1YTkxNjQxMTY2MjA3NWZiZTZhNjlmYmY4NThkODM4NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dyI-Ffpe3SA17N4sblWnAj6y0PIZCpduskdqcdspmTw">

BeplnEX版本为：v5.4.23.1
liar bar 版本为steam最新版本
.NET版本为 8.0

**Comment by na20215** [comment]
其实你提供的版本直接就可以使用，不过最新版我成了无头骑士，不知道是不是版本更新的原因

**Comment by dogdie233** [comment]
> 其实你提供的版本直接就可以使用，不过最新版我成了无头骑士，不知道是不是版本更新的原因

可能只是自己看不见自己的头

**Comment by dogdie233** [comment]
> > 哥你图没发上来
> 
> 这哥们太逗了，我估计是这次更新文件出现变动了吧。 确实失败了： C:\Users\10433\Downloads\LiarsBarEnhance-master\Features\RemoveHeadRotationlimitPatch.cs(14,13): warning Harmony003: Ha rmony non-ref patch parameter lfAngle += 360f modified. This assignment have no effect. [C:\Users\10433\Downloads\Liars BarEnhance-master\LiarsBarEnhance.csproj] C:\Users\10433\Downloads\LiarsBarEnhance-master\Features\RemoveHeadRotationlimitPatch.cs(16,13): warning Harmony003: Ha rmony non-ref patch parameter lfAngle -= 360f modified. This assignment have no effect. [C:\Users\10433\Downloads\Liars BarEnhance-master\LiarsBarEnhance.csproj] C:\Users\10433\Downloads\LiarsBarEnhance-master\Plugin.cs(28,42): error CS0246: 未能找到类型或命名空间名“SelectableLevelPatch”(是否缺少 using 指令或程序集引用?) [C:\Users\10433\Downloads\LiarsBarEnhance-master\LiarsBarEnhance.csproj] C:\Users\10433\Downloads\LiarsBarEnhance-master\Plugin.cs(28,72): error CS0103: 当前上下文中不存在名称“SelectableLevelPatch” [C:\U sers\10433\Downloads\LiarsBarEnhance-master\LiarsBarEnhance.csproj] 2 个警告 2 个错误

我的，处理冲突的时候手贱了，现在可以了
